src/Entity/Activity.php
<?php
declare(strict_types=1);

namespace App\Entity;

final class Activity
{
    private int $id;
    private ?int $project_id;
    private string $name;
    private ?string $color;
    private ?string $number;
    private ?string $comment;
    private int $visible;
    private ?string $created_at;


    public function getId() {
        return $this->id;
    }

    public function setId($id) {
        $this->id = $id;
        return $this;
    }


    public function getProjectId() {
        return $this->project_id;
    }

    public function setProjectId($project_id) {
        $this->project_id = $project_id;
        return $this;
    }


    public function getName() {
        return $this->name;
    }

    public function setName($name) {
        $this->name = $name;
        return $this;
    }


    public function getColor() {
        return $this->color;
    }

    public function setColor($color) {
        $this->color = $color;
        return $this;
    }


    public function getNumber() {
        return $this->number;
    }

    public function setNumber($number) {
        $this->number = $number;
        return $this;
    }


    public function getComment() {
        return $this->comment;
    }

    public function setComment($comment) {
        $this->comment = $comment;
        return $this;
    }


    public function getVisible() {
        return $this->visible;
    }

    public function setVisible($visible) {
        $this->visible = $visible;
        return $this;
    }


    public function getCreatedAt() {
        return $this->created_at;
    }

    public function setCreatedAt($created_at) {
        $this->created_at = $created_at;
        return $this;
    }

}

src/Entity/Timesheet.php
<?php
declare(strict_types=1);

namespace App\Entity;

final class Timesheet
{
    private int $id;
    private int $user_id;
    private int $activity_id;
    private int $project_id;
    private string $start;
    private ?string $end;
    private ?int $duration;
    private ?string $comment;
    private ?string $modified_at;


    public function getId() {
        return $this->id;
    }

    public function setId($id) {
        $this->id = $id;
        return $this;
    }


    public function getUserId() {
        return $this->user_id;
    }

    public function setUserId($user_id) {
        $this->user_id = $user_id;
        return $this;
    }


    public function getActivityId() {
        return $this->activity_id;
    }

    public function setActivityId($activity_id) {
        $this->activity_id = $activity_id;
        return $this;
    }


    public function getProjectId() {
        return $this->project_id;
    }

    public function setProjectId($project_id) {
        $this->project_id = $project_id;
        return $this;
    }


    public function getStart() {
        return $this->start;
    }

    public function setStart($start) {
        $this->start = $start;
        return $this;
    }


    public function getEnd() {
        return $this->end;
    }

    public function setEnd($end) {
        $this->end = $end;
        return $this;
    }


    public function getDuration() {
        return $this->duration;
    }

    public function setDuration($duration) {
        $this->duration = $duration;
        return $this;
    }


    public function getComment() {
        return $this->comment;
    }

    public function setComment($comment) {
        $this->comment = $comment;
        return $this;
    }


    public function getModifiedAt() {
        return $this->modified_at;
    }

    public function setModifiedAt($modified_at) {
        $this->modified_at = $modified_at;
        return $this;
    }

}

templates/activities.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{trans.view_activities }}{% endblock %}

{% block navbar %}
    {% embed 'navbar.html.twig' with {'title': trans.view_activities, 'navLinks': navLinks } %}{% endembed %}
{% endblock %}

{% block content %}
    {% embed 'toast-messages.html.twig' %}{% endembed %}

    {% if userRole in [2, 3] %}
    <div class="d-flex justify-content-end py-2">
        <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#createActivity">
            <i class="bi bi-plus-lg"></i>
            <span class="px-1">{{ trans.btn_create }}</span>
        </button>
    </div>
    {% endif %}

    <div class="card mb-3">
        <div class="card-body table-responsive">

            <table class="table table-hover" id="datatable">
                <thead>
                    <tr>
                        <th scope="col">{{ trans.table_row_name }}</th>
                        <th scope="col">{{ trans.table_row_number }}</th>
                        <th scope="col">{{ trans.table_row_project }}</th>
                        <th scope="col">{{ trans.table_row_description }}</th>
                        <th scope="col" class="nosearch">{{ trans.table_row_teams }}</th>
                        <th scope="col">{{ trans.table_row_visible }}</th>
                        <th scope="col" class="nosearch"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for activity in activities %}
                        <tr>
                            <td>
                                <div class="d-inline-flex align-items-center text-nowrap">
                                    <span class="badge p-1 border border-light rounded-circle" style="background-color: {{ activity.color }};"><span class="visually-hidden">color</span></span>
                                    <span class="ms-1">{{ activity.name }}</span>
                                </div>
                            </td>
                            <td>{{ activity.number }}</td>
                            <td>
                                {% if activity.projectName is defined %}
                                    <div class="d-inline-flex align-items-center text-nowrap">
                                        <span class="badge p-1 border border-light rounded-circle" style="background-color: {{ activity.projectColor }};"><span class="visually-hidden">color</span></span>
                                        <span class="ms-1">{{ activity.projectName }}</span>
                                    </div>
                                {% endif %}
                            </td>
                            <td>{{ activity.comment|nl2br }}</td>
                            <td>
                                <span class="float-start badge {{ activity.teamsCount == 0 ? "text-bg-secondary" : "text-bg-primary" }} ">{{ activity.teamsCount }}</span>
                            </td>
                            <td>
                                {% if activity.visible == true %}
                                    <span class="badge text-bg-success">{{ trans.badge_yes }}</span>
                                {% else %}
                                    <span class="badge text-bg-danger">{{ trans.badge_no }}</span>
                                {% endif %}
                            </td>
                            <td>
                                <div class="float-end text-nowrap">
                                    <a class="icon-link icon-link-hover mx-2" href="{{ activity.viewLink }}">
                                        <i class="bi bi-eye"></i>
                                    </a>
                                    {% if userRole == 3 or (userRole == 2 and activity.teamsCount > 0) %}
                                    <a class="icon-link icon-link-hover mx-2" href="{{ activity.editLink }}">
                                        <i class="bi bi-pencil"></i>
                                    </a>
                                    {% endif %}

                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% if userRole in [2, 3] %}
    <div class="modal fade" id="createActivity" tabindex="-1" aria-labelledby="createActivityLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form name="activity_edit_form" method="post" autocomplete="off">

                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="createActivityLabel">{{ trans.form_title_create_activity }}</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="modal-body">
                        <div class="row mb-3">
                            <label for="activity_edit_form_name" class="col-form-label col-sm-3">{{ trans.form_label_name }}</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="activity_edit_form_name" name="activity_edit_form_name" placeholder="{{ trans.form_label_name }}" minlength="5" maxlength="180" required="required" tabindex="1">
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="activity_edit_form_color" class="col-form-label col-sm-3">{{ trans.form_label_color }}</label>
                            <div class="col-sm-9">
                                <div class="dropdown">
                                    <input type="color" class="form-control form-control-color form-control-color-select" id="activity_edit_form_color" name="activity_edit_form_color" data-bs-toggle="dropdown" value="#ffffff">
                                    <div class="dropdown-menu" id="activity_edit_form_colorselector">
                                        {% for color in colors %}
                                            <span class="btn btn-select-color m-1 p-2 border" style="background-color:{{ color.value }};" id="team_edit_form_color_entry" data-color="{{ color.value }}"></span>
                                            {% if loop.index is divisible by(6) %}
                                                <br>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="activity_edit_form_project" class="col-form-label col-sm-3">{{ trans.form_label_project }}</label>
                            <div class="col-sm-9">
                                <select class="form-select" id="activity_edit_form_project" name="activity_edit_form_project" tabindex="3">
                                    <option selected value=""></option>
                                    {% for project in projects %}
                                        <option value="{{ project.id }}">{{ project.name }}</option>
                                    {% endfor %}
                                </select>
                                <div class="form-text">{{ trans.form_text_add_project|nl2br }}</div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="activity_edit_form_number" class="col-form-label col-sm-3">{{ trans.form_label_activity_number }}</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="activity_edit_form_number" name="activity_edit_form_number" placeholder="{{ trans.form_label_activity_number }}" minlength="0" maxlength="50" tabindex="4">
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="activity_edit_form_description" class="col-form-label col-sm-3">{{ trans.form_label_description }}</label>
                            <div class="col-sm-9">
                                <textarea class="form-control" id="activity_edit_form_description" name="activity_edit_form_description" rows="3" tabindex="5"></textarea>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="activity_edit_form_teams" class="col-form-label col-sm-3">{{ trans.form_label_add_team }}</label>
                            <div class="col-sm-9">
                                <select class="form-select" id="activity_edit_form_teams" name="activity_edit_form_teams" tabindex="6">
                                    <option selected value=""></option>
                                    {% for team in teams %}
                                        <option value="{{ team.id }}">{{ team.name }}</option>
                                    {% endfor %}
                                </select>
                                <div class="form-text">{{ trans.form_text_add_team }}</div>
                            </div>
                        </div>
                        <div class="mb-3" id="activity_edit_form_selectedTeams">
                            <div class="row mb-3">
                                <div class="col-sm-9 offset-sm-3">
                                    {{ trans.form_label_selected_teams }}
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <div class="form-check form-switch">
                                    <input class="form-check-input" type="checkbox" role="switch" id="activity_edit_form_visible" name="activity_edit_form_visible" tabindex="7" checked>
                                    <label class="form-check-label" for="activity_edit_form_visible">{{ trans.form_label_visible }}</label>
                                    <div class="form-text">{{ trans.form_text_visible }}</div>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ trans.btn_close }}</button>
                        <button type="submit" class="btn btn-primary">{{ trans.btn_save }}</button>
                        <input type="hidden" name="{{ csrf.nameKey | raw }}" value="{{ csrf.name | raw }}">
                        <input type="hidden" name="{{ csrf.valueKey | raw }}" value="{{ csrf.value | raw }}">
                    </div>

                </form>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block scripts %}
    <script nonce="{{ nonce }}" src="{{ basePath }}/js/activities.js"></script>
    <script nonce="{{ nonce }}" src="{{ basePath }}/js/dataTables.js"></script>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">

    <link rel="icon" type="image/png" href="{{ basePath }}/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/svg+xml" href="{{ basePath }}/favicon.svg">
    <link rel="shortcut icon" href="{{ basePath }}/favicon.ico">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ basePath }}/apple-touch-icon.png">
    <meta name="apple-mobile-web-app-title" content="Tacos">
    <link rel="manifest" href="{{ basePath }}/manifest.json">

    <title>Tacos | {% block title %}{% endblock %}</title>

    <link href="{{ basePath }}/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ basePath }}/lib/bootstrap-icons/bootstrap-icons.min.css" rel="stylesheet">
    <link href="{{ basePath }}/lib/datatables/dataTables.bootstrap5.min.css" rel="stylesheet">
    {% block css %}{% endblock %}
    <link href="{{ basePath }}/css/theme.css" rel="stylesheet">
</head>
<body class="border-top border-primary" basepath="{{ basePath is empty ? "" : basePath }}" >
    {% block navbar %}{% endblock %}
    <div class="container-fluid container-max-width">
        {% block content %}{% endblock %}
    </div>

    <script nonce="{{ nonce }}" src="{{ basePath }}/lib/jquery/jquery-3.7.1.min.js"></script>
    <script nonce="{{ nonce }}" src="{{ basePath }}/lib/popper/popper.min.js"></script>
    <script nonce="{{ nonce }}" src="{{ basePath }}/lib/bootstrap/js/bootstrap.min.js"></script>
    <script nonce="{{ nonce }}" src="{{ basePath }}/lib/datatables/dataTables.min.js"></script>
    <script nonce="{{ nonce }}" src="{{ basePath }}/lib/datatables/dataTables.bootstrap5.min.js"></script>

    <script nonce="{{ nonce }}" src="{{ basePath }}/js/functions.js"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

templates/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{trans.view_dashboard }}{% endblock %}

{% block navbar %}
    {% embed 'navbar.html.twig' with {'title': trans.view_dashboard, 'navLinks': navLinks } %}{% endembed %}
{% endblock %}

{% block content %}
    <div class="card mb-3">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-borderless w-auto">
                    <tbody>
                        <tr>
                            <th scope="row"><i class="bi bi-hourglass text-bg-danger"></i> {{ trans.table_row_active_records }}</th>
                            <td>{{ activeRecords }}</td>
                        </tr>
                        <tr>
                            <th scope="row"><i class="bi bi-hourglass"></i> {{ trans.table_row_workingHours_today }}</th>
                            <td>{{ workingHours.today }}</td>
                        </tr>
                        <tr>
                            <th scope="row"><i class="bi bi-hourglass"></i> {{ trans.table_row_workingHours_week }}</th>
                            <td>{{ workingHours.week }}</td>
                        </tr>
                        <tr>
                            <th scope="row"><i class="bi bi-hourglass"></i> {{ trans.table_row_workingHours_lastweek }}</th>
                            <td>{{ workingHours.lastweek }}</td>
                        </tr>
                        <tr>
                            <th scope="row"><i class="bi bi-hourglass"></i> {{ trans.table_row_workingHours_month }}</th>
                            <td>{{ workingHours.month }}</td>
                        </tr>
                        <tr>
                            <th scope="row"><i class="bi bi-hourglass"></i> {{ trans.table_row_workingHours_lastmonth }}</th>
                            <td>{{ workingHours.lastmonth }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{trans.view_login}}{% endblock %}

{% block content %}
    <div class="text-center my-4">
        <img src="{{ basePath }}/img/tacos.png" class="img-fluid rounded-circle mb-2" alt="tacos">
    </div>

    <div class="login-box mx-auto d-block px-4 py-4 border rounded">
        {% if flashMsgError is not null %}
            <div class="alert alert-important alert-danger">{{ flashMsgError }}</div>
        {% endif %}
        {% if message is not null %}
            <div class="alert alert-important alert-primary">{{ message }}</div>
        {% endif %}
        <h2 class="form-title text-center mb-4">{{ trans.form_title_login }}</h2>
        <form method="post" autocomplete="off">
            <div class="mb-3">
                <label for="login" class="form-label">{{ trans.form_label_login }}</label>
                <input type="text" class="form-control" id="login" name="_login" autocomplete="username" placeholder="{{ trans.form_label_login }}" required="required" tabindex="1">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">{{ trans.form_label_password }}</label>
                <span class="form-text float-end"><a href="{{ password_forgot_url }}" tabindex="4">{{ trans.form_label_password_forgot }}</a></span>
                <input type="password" class="form-control" id="password" name="_password" autocomplete="new-password" placeholder="{{ trans.form_label_password }}" required="required" tabindex="2">
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary w-100" tabindex="3">{{ trans.btn_login }}</button>
            </div>
            <input type="hidden" name="{{ csrf.nameKey | raw }}" value="{{ csrf.name | raw }}">
            <input type="hidden" name="{{ csrf.valueKey | raw }}" value="{{ csrf.value | raw }}">
        </form>
    </div>
{% endblock %}

templates/timesheet-edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{trans.view_timesheet}}{% endblock %}

{% block css %}
    <link href="{{ basePath }}/css/container-max-width.css" rel="stylesheet">
    <link href="{{ basePath }}/lib/tempus-dominus/tempus-dominus.min.css" rel="stylesheet">
{% endblock %}

{% block navbar %}
    {% embed 'navbar.html.twig' with {'title': trans.view_timesheet, 'navLinks': navLinks } %}{% endembed %}
{% endblock %}

{% block content %}
    {% embed 'toast-messages.html.twig' %}{% endembed %}

    <div class="d-flex justify-content-end py-2">
         <a class="btn btn-close" href="{{ navLinks.timesheets }}" role="button"></a>
    </div>

    <div class="card mb-3">
        <div class="card-header fs-5 fw-bold">
            {{ trans.form_title_edit_timesheet_record }}
        </div>

        <form name="timesheet_edit_form" method="post" autocomplete="off">
            <div class="card-body">

                <div class="row mb-3">
                    <div class="col-sm-2">
                        <label for="timesheet_edit_form_start_date" class="col-form-label">{{ trans.form_label_timesheet_start }}</label>
                    </div>

                    <div class="col-sm-5">
                        <div class="input-group" id="pickerStartDate" data-td-target-input="nearest" data-td-target-toggle="nearest">
                            <span class="input-group-text" data-td-target="#pickerStartDate" data-td-toggle="datetimepicker">
                                <i class="bi bi-calendar2-week"></i>
                            </span>
                            <input id="timesheet_edit_form_start_date" name="timesheet_edit_form_start_date" type="text" class="form-control" data-td-target="#pickerStartDate" value="{{ timesheet.start is empty ? "" : timesheet.start|date(trans.dateFormats_date) }}" placeholder="{{ trans.dateFormats_date_placeholder }}" tabindex="1" required="required" readonly>
                        </div>
                    </div>

                    <div class="col-sm-5">
                        <div class="input-group" id="pickerStartTime" data-td-target-input="nearest" data-td-target-toggle="nearest">
                            <span class="input-group-text" data-td-target="#pickerStartTime" data-td-toggle="datetimepicker">
                                <i class="bi bi-clock"></i>
                            </span>
                            <input id="timesheet_edit_form_start_time" name="timesheet_edit_form_start_time" type="text" class="form-control" data-td-target="#pickerStartTime" value="{{ timesheet.start is empty ? "" : timesheet.start|date(trans.dateFormats_time) }}" placeholder="{{ trans.dateFormats_time_placeholder }}" tabindex="2" required="required" readonly>
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-sm-2">
                        <label for="timesheet_edit_form_duration" class="col-form-label">{{ trans.form_label_timesheet_end }}</label>
                    </div>

                    <div class="col-sm-5">
                        <div class="input-group" id="pickerDuration" data-td-target-input="nearest" data-td-target-toggle="nearest">
                            <span class="input-group-text" data-td-target="#pickerDuration" data-td-toggle="datetimepicker">
                                <i class="bi bi-hourglass"></i>
                            </span>
                            <input id="timesheet_edit_form_duration" name="timesheet_edit_form_duration" type="text" class="form-control" data-td-target="#pickerDuration" value="{{ durationTmp }}" placeholder="{{ trans.dateFormats_time_placeholder }}" tabindex="3" readonly>
                        </div>
                    </div>

                    <div class="col-sm-5">
                        <div class="input-group" id="pickerEndTime" data-td-target-input="nearest" data-td-target-toggle="nearest">
                            <span class="input-group-text" data-td-target="#pickerEndTime" data-td-toggle="datetimepicker">
                                <i class="bi bi-clock"></i>
                            </span>
                            <input id="timesheet_edit_form_end_time" name="timesheet_edit_form_end_time" type="text" class="form-control" data-td-target="#pickerEndTime" value="{{ timesheet.end is empty ? "" : timesheet.end|date(trans.dateFormats_time) }}" placeholder="{{ trans.dateFormats_time_placeholder }}" tabindex="4" readonly>
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="timesheet_edit_form_customer" class="col-form-label col-sm-2">{{ trans.form_label_customer }}</label>
                    <div class="col-sm-10">
                        <select class="form-select" id="timesheet_edit_form_customer" name="timesheet_edit_form_customer" tabindex="5">
                            <option value="" selected></option>
                            {% for customer in customers %}
                                <option value="{{ customer.id }}">{{ customer.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="timesheet_edit_form_project" class="col-form-label col-sm-2">{{ trans.form_label_project }}</label>
                    <div class="col-sm-10">
                        <select class="form-select" id="timesheet_edit_form_project" name="timesheet_edit_form_project" required="required" tabindex="6">
                            <option value="" selected></option>
                            {% for project in projects %}
                                <option value="{{ project.id }}" {% if timesheet.projectId == project.id %}selected{% endif %}>{{ project.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="timesheet_edit_form_activity" class="col-form-label col-sm-2">{{ trans.form_label_activity }}</label>
                    <div class="col-sm-10">
                        <select class="form-select" id="timesheet_edit_form_activity" name="timesheet_edit_form_activity" required="required" tabindex="7">
                            <option selected value=""></option>
                            {% for activity in activities %}
                                <option value="{{ activity.id }}" {% if timesheet.activityId == activity.id %}selected{% endif %} {% if activity.id not in projectActivitiesIds %}hidden disabled{% endif %}>{{ activity.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="timesheet_edit_form_description" class="col-form-label col-sm-2">{{ trans.form_label_description }}</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="timesheet_edit_form_description" name="timesheet_edit_form_description" rows="3" tabindex="8">{{ timesheet.comment }}</textarea>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="timesheet_edit_form_tags" class="col-form-label col-sm-2">{{ trans.form_label_tags }}</label>
                    <div class="col-sm-10">
                        <select class="form-select" id="timesheet_edit_form_tags" name="timesheet_edit_form_tags" tabindex="7">
                            <option selected value=""></option>
                            {% for tag in tags %}
                                <option value="{{ tag.id }}" color="{{ tag.color }}" {% if tag.id in selectedTagsIds %}hidden disabled{% endif %}>{{ tag.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-10 offset-sm-2 d-flex" id="timesheet_edit_form_selectedTags">
                        {% for selectedTag in selectedTags %}
                            <div class="me-2" id="timesheet_edit_form_tags_{{ selectedTag.id }}">
                                <input type="hidden" name="timesheet_edit_form[selectedTags][]" value="{{ selectedTag.id }}" required="required">
                                <span class="btn-remove-member badge" style="background-color: {{ selectedTag.color }};" value="{{ selectedTag.id }}">{{ selectedTag.name }}<i class="bi bi-x ms-1 border-start"></i></span>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>



            <div class="card-footer">
                <div class="mb-3 float-end">
                    <button type="submit" class="btn btn-primary" tabindex="8">
                        <i class="bi bi-floppy"></i>
                        <span class="px-1">{{ trans.btn_save }}</span>
                    </button>
                </div>

                <input type="hidden" name="{{ csrf.nameKey | raw }}" value="{{ csrf.name | raw }}">
                <input type="hidden" name="{{ csrf.valueKey | raw }}" value="{{ csrf.value | raw }}">
                <input type="hidden" id="dateFormats_L" value="{{ trans.dateFormats_L }}">
                <input type="hidden" id="dateFormats_LT" value="{{ trans.dateFormats_LT }}">
                <input type="hidden" id="dateFormats_startOfTheWeek" value="{{ trans.dateFormats_startOfTheWeek }}">
                <input type="hidden" id="startDate" value="{{ timesheet.start }}" >
                <input type="hidden" id="endDate" value="{{ timesheet.end }}" >
            </div>
        </form>

    </div>
{% endblock %}

{% block scripts %}
    <script nonce="{{ nonce }}" src="{{ basePath }}/lib/tempus-dominus/tempus-dominus.min.js"></script>
    <script nonce="{{ nonce }}" src="{{ basePath }}/js/tempus.js"></script>
    <script nonce="{{ nonce }}" src="{{ basePath }}/js/timesheets.js"></script>
{% endblock %}